name: CI

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name:  Repository Checkout
      uses: actions/checkout@v2

    - name:  Dependencies Installation
      run: npm install

    - name: Results Testing
      run: echo "Tests Passed"
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2

    - name: Dependencies Installation
      run: npm install

    - name: Run Linting
      run: npm run lint
      continue-on-error: ${{ matrix.os != 'windows-latest' }}

    - name: Check Test Results
      if: ${{ always() }}
      run: echo "Tests Passed"
